"""initial schema

Revision ID: ce298c799493
Revises: 
Create Date: 2026-09-27 12:01:47.289494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.db.models import Vector384


revision: str = 'ce298c799493'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('usage_hours', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('usage_hours', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpu_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('gpu_id', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('utilization_pct', sa.Float(), nullable=True),
    sa.Column('vram_used_mb', sa.Float(), nullable=True),
    sa.Column('power_watts', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpu_optimization_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('gpu_id', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('utilization_pct', sa.Float(), nullable=True),
    sa.Column('power_watts', sa.Float(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('estimated_monthly_waste_usd', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('host_id', sa.String(), nullable=False),
    sa.Column('cpu_pct', sa.Float(), nullable=True),
    sa.Column('memory_pct', sa.Float(), nullable=True),
    sa.Column('disk_pct', sa.Float(), nullable=True),
    sa.Column('network_receive_bytes_per_second', sa.Float(), nullable=True),
    sa.Column('network_transmit_bytes_per_second', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'source', 'source_key', name='uq_ingestion_event')
    )
    op.create_table('k8s_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('pod_name', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operational_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector384(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_ref'], ['operational_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waste_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('billing_record_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('waste_type', sa.String(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('estimated_monthly_waste_usd', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_record_id'], ['billing_records.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('estimated_savings_usd', sa.Float(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('waste_finding_id', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('dollar_savings', sa.Float(), nullable=True),
    sa.Column('carbon_savings_kg', sa.Float(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['waste_finding_id'], ['waste_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('accepted', sa.String(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_feedback')
    op.drop_table('audit_logs')
    op.drop_table('recommendations')
    op.drop_table('waste_items')
    op.drop_table('log_embeddings')
    op.drop_table('user_profiles')
    op.drop_table('operational_logs')
    op.drop_table('k8s_metrics')
    op.drop_table('ingestion_records')
    op.drop_table('infrastructure_metrics')
    op.drop_table('gpu_optimization_findings')
    op.drop_table('gpu_metrics')
    op.drop_table('billing_records')
    op.drop_table('anomaly_findings')
    op.drop_table('alerts')
    op.drop_table('organizations')
    # ### end Alembic commands ###
