import {
  LayoutGrid,
  LineChart,
  Sparkles,
  Bell,
  Leaf,
  Settings,
  Search,
  Sun,
  Moon,
  CreditCard,
  Zap,
  Hourglass,
  Server,
  Monitor,
  Database,
  Boxes,
  Lightbulb,
  MessageCircle,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  Check,
  Clock,
  ShieldCheck,
  Cloud,
  KeyRound,
  Mail,
  Lock,
  User,
  Building2,
  CircleCheck,
  X,
  Send,
  LoaderCircle,
} from "lucide-react";

// Semantic key -> component. Add new icons here so the rest of the
// app never imports lucide-react directly.
export const ICONS = {
  dashboard: LayoutGrid,
  analytics: LineChart,
  insights: Sparkles,
  alerts: Bell,
  greenops: Leaf,
  settings: Settings,
  search: Search,
  sun: Sun,
  moon: Moon,
  creditCard: CreditCard,
  zap: Zap,
  leaf: Leaf,
  hourglass: Hourglass,
  server: Server,
  monitor: Monitor,
  database: Database,
  boxes: Boxes,
  lightbulb: Lightbulb,
  assistant: MessageCircle,
  chevronRight: ChevronRight,
  up: ArrowUp,
  down: ArrowDown,
  check: Check,
  clock: Clock,
  shield: ShieldCheck,
  cloud: Cloud,
  key: KeyRound,
  mail: Mail,
  lock: Lock,
  user: User,
  building: Building2,
  circleCheck: CircleCheck,
  close: X,
  send: Send,
  loading: LoaderCircle,
};

export function Icon({ name, ...props }) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp {...props} />;
}
